version: '3'

services:
  web:
    image: node:14.15
    working_dir: /usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    env_file: .env
    volumes:
      - .:/usr/src/app
    command: ['npm', 'run', 'dev']

  db:
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
